const { buildFieldMapping, previewTransformation } = require('../src/fieldMapper');

describe('fieldMapper', () => {
    describe('buildFieldMapping', () => {
        const mockSource = {
            dataHeaders: ['姓名', '证件号码', '手机号', '企业缴费', '个人缴费']
        };

        const mockTarget = {
            headerKeyValues: [],
            dataHeaders: ['姓名', '证件编号', '联系电话', '企业缴费金额', '个人缴费金额']
        };

        test('should build correct mapping for exact match', () => {
            const mapping = buildFieldMapping(mockSource, mockTarget);
            
            expect(mapping.columnMappings.length).toBeGreaterThan(0);
            
            const nameMapping = mapping.columnMappings.find(m => m.targetField === '姓名');
            expect(nameMapping).toBeDefined();
            expect(nameMapping.sourceField).toBe('姓名');
            expect(nameMapping.score).toBe(100);
        });

        test('should build correct mapping for partial match', () => {
            const mapping = buildFieldMapping(mockSource, mockTarget);
            
            const phoneMapping = mapping.columnMappings.find(m => m.targetField === '联系电话');
            expect(phoneMapping).toBeDefined();
            expect(phoneMapping.sourceField).toBe('手机号');
        });

        test('should identify auto-generated columns', () => {
            const sourceWithSeq = {
                dataHeaders: ['序号', '姓名']
            };
            const targetWithSeq = {
                headerKeyValues: [],
                dataHeaders: ['序号', '姓名']
            };
            
            const mapping = buildFieldMapping(sourceWithSeq, targetWithSeq);
            
            expect(mapping.autoGeneratedColumns.length).toBe(1);
            expect(mapping.autoGeneratedColumns[0].targetField).toBe('序号');
        });

        test('should identify calculated columns', () => {
            const source = { dataHeaders: ['金额1', '金额2'] };
            const target = {
                headerKeyValues: [],
                dataHeaders: ['金额1', '金额2', '合计']
            };
            
            const mapping = buildFieldMapping(source, target);
            
            expect(mapping.calculatedColumns.length).toBe(1);
            expect(mapping.calculatedColumns[0].targetField).toBe('合计');
        });

        test('should track missing fields', () => {
            const source = { dataHeaders: ['姓名'] };
            const target = {
                headerKeyValues: [],
                dataHeaders: ['姓名', '不存在的字段']
            };
            
            const mapping = buildFieldMapping(source, target);
            
            expect(mapping.missingDataFields).toContain('不存在的字段');
        });
    });

    describe('previewTransformation', () => {
        test('should correctly identify mapped fields', () => {
            const source = { dataHeaders: ['姓名', '年龄'] };
            const target = { 
                dataHeaders: ['姓名', '年龄', '地址'] 
            };
            const mapping = {
                columnMappings: [
                    { sourceIndex: 0, targetIndex: 0, sourceField: '姓名', targetField: '姓名', score: 100 },
                    { sourceIndex: 1, targetIndex: 1, sourceField: '年龄', targetField: '年龄', score: 100 }
                ],
                autoGeneratedColumns: [],
                calculatedColumns: []
            };
            
            const preview = previewTransformation(source, target, mapping);
            
            expect(preview.mappedFields.length).toBe(2);
            expect(preview.missingOptionalFields.length).toBe(1);
        });

        test('should correctly identify required fields', () => {
            const source = { dataHeaders: ['姓名'] };
            const target = { 
                dataHeaders: ['姓名*', '年龄'] 
            };
            const mapping = {
                columnMappings: [
                    { sourceIndex: 0, targetIndex: 0, sourceField: '姓名', targetField: '姓名*', score: 100 }
                ],
                autoGeneratedColumns: [],
                calculatedColumns: []
            };
            
            const preview = previewTransformation(source, target, mapping);
            
            expect(preview.summary.required).toBe(1);
            expect(preview.summary.requiredMissing).toBe(0);
        });

        test('should calculate summary correctly', () => {
            const source = { dataHeaders: ['A', 'B'] };
            const target = { 
                dataHeaders: ['A', 'B', 'C', 'D'] 
            };
            const mapping = {
                columnMappings: [
                    { sourceIndex: 0, targetIndex: 0, sourceField: 'A', targetField: 'A', score: 100 }
                ],
                autoGeneratedColumns: [],
                calculatedColumns: []
            };
            
            const preview = previewTransformation(source, target, mapping);
            
            expect(preview.summary.total).toBe(4);
            expect(preview.summary.mapped).toBe(1);
        });
    });
});
