const config = require('./config');

function buildFieldMapping(source, target) {
    const mapping = {
        headerMappings: [],
        columnMappings: [],
        autoGeneratedColumns: [],
        calculatedColumns: [],
        missingHeaderFields: [],
        missingDataFields: []
    };
    
    target.headerKeyValues.forEach(hkv => {
        const keyLower = hkv.key.toLowerCase();
        const found = source.dataHeaders.some(sh => {
            const shLower = sh.toLowerCase();
            return shLower.includes(keyLower) || keyLower.includes(shLower);
        });
        
        if (!found) {
            mapping.missingHeaderFields.push({
                field: hkv.key,
                currentValue: hkv.value,
                location: `表头区域第${hkv.row + 1}行`
            });
        }
        
        mapping.headerMappings.push({
            targetField: hkv.key,
            targetValue: hkv.value,
            sourceField: found ? '已映射' : '未找到'
        });
    });
    
    const autoGenKeywords = config.mapping.autoGenKeywords;
    const calcKeywords = config.mapping.calcKeywords;
    
    const semanticMappings = config.mapping.semanticMappings;
    
    function findSemanticMatch(targetField, sourceHeaders) {
        const targetLower = targetField.toLowerCase().replace(/[=\(\)（）\*]/g, '').replace(/f\+g|i\+j|e\+h|n\+o/gi, '').trim();
        
        for (const map of semanticMappings) {
            const targetMatch = map.target.some(t => {
                const tLower = t.toLowerCase();
                return targetLower.includes(tLower) || tLower.includes(targetLower);
            });
            
            if (targetMatch) {
                for (let sIdx = 0; sIdx < sourceHeaders.length; sIdx++) {
                    const sh = sourceHeaders[sIdx];
                    if (!sh) continue;
                    const shLower = sh.toLowerCase().replace(/[=\(\)（）\*]/g, '').trim();
                    
                    const sourceMatch = map.source.some(s => {
                        const sLower = s.toLowerCase();
                        return shLower.includes(sLower) || sLower.includes(shLower);
                    });
                    
                    if (sourceMatch) {
                        return { sourceField: sh, sourceIndex: sIdx, score: 85, matchType: 'semantic' };
                    }
                }
            }
        }
        return null;
    }
    
    target.dataHeaders.forEach((th, idx) => {
        if (!th) return;
        
        const thLower = th.toLowerCase();
        
        if (autoGenKeywords.some(kw => thLower.includes(kw)) && thLower.length <= 4) {
            mapping.autoGeneratedColumns.push({
                targetField: th,
                targetIndex: idx,
                type: 'auto_increment'
            });
            return;
        }
        
        if (calcKeywords.some(kw => thLower.includes(kw))) {
            mapping.calculatedColumns.push({
                targetField: th,
                targetIndex: idx,
                type: 'calculated'
            });
            return;
        }
        
        let bestMatch = null;
        let bestScore = 0;
        
        const semanticMatch = findSemanticMatch(th, source.dataHeaders);
        if (semanticMatch) {
            bestMatch = semanticMatch;
            bestScore = semanticMatch.score;
        }
        
        source.dataHeaders.forEach((sh, sIdx) => {
            if (!sh) return;
            const shLower = sh.toLowerCase();
            let score = 0;
            
            const thClean = thLower.replace(/\*/g, '').trim();
            const shClean = shLower.replace(/\*/g, '').trim();
            
            if (thClean === shClean) {
                score = 100; // 精确匹配返回100分
            } else {
                const thWords = thClean.split(/[\s_\-：:]+/).filter(w => w.length > 0);
                const shWords = shClean.split(/[\s_\-：:]+/).filter(w => w.length > 0);
                const commonWords = thWords.filter(w => shWords.some(sw => sw.includes(w) || w.includes(sw)));
                
                if (commonWords.length > 0) {
                    score = 60;
                } else {
                    score = 0;
                }
            }
            
            if (score > bestScore) {
                bestScore = score;
                bestMatch = { sourceField: sh, sourceIndex: sIdx, score };
            }
        });
        
        if (bestMatch && bestScore >= 30) {
            mapping.columnMappings.push({
                targetField: th,
                targetIndex: idx,
                sourceField: bestMatch.sourceField,
                sourceIndex: bestMatch.sourceIndex,
                score: bestMatch.score,
                matchType: bestMatch.matchType || 'text'
            });
        } else {
            mapping.missingDataFields.push(th);
        }
    });
    
    return mapping;
}

function previewTransformation(source, target, mapping) {
    const result = {
        targetFields: [],
        missingRequiredFields: [],
        missingOptionalFields: [],
        mappedFields: [],
        autoGeneratedFields: [],
        calculatedFields: [],
        summary: {
            total: 0,
            mapped: 0,
            missing: 0,
            required: 0,
            requiredMissing: 0
        }
    };
    
    const mappedTargetIndices = new Set();
    mapping.columnMappings.forEach(m => mappedTargetIndices.add(m.targetIndex));
    mapping.autoGeneratedColumns.forEach(c => mappedTargetIndices.add(c.targetIndex));
    mapping.calculatedColumns.forEach(c => mappedTargetIndices.add(c.targetIndex));
    
    target.dataHeaders.forEach((header, idx) => {
        if (!header) return;
        
        const isRequired = header.includes('*');
        const cleanHeader = header.replace(/\*/g, '').trim();
        
        const fieldInfo = {
            name: cleanHeader,
            originalName: header,
            index: idx,
            isRequired: isRequired,
            sourceField: null,
            status: 'missing'
        };
        
        const columnMapping = mapping.columnMappings.find(m => m.targetIndex === idx);
        if (columnMapping) {
            fieldInfo.sourceField = columnMapping.sourceField;
            fieldInfo.status = 'mapped';
            fieldInfo.matchScore = columnMapping.score;
            result.mappedFields.push(fieldInfo);
        } else {
            const autoCol = mapping.autoGeneratedColumns.find(c => c.targetIndex === idx);
            if (autoCol) {
                fieldInfo.status = 'auto_generated';
                result.autoGeneratedFields.push(fieldInfo);
            } else {
                const calcCol = mapping.calculatedColumns.find(c => c.targetIndex === idx);
                if (calcCol) {
                    fieldInfo.status = 'calculated';
                    result.calculatedFields.push(fieldInfo);
                } else {
                    fieldInfo.status = 'missing';
                    if (isRequired) {
                        result.missingRequiredFields.push(fieldInfo);
                    } else {
                        result.missingOptionalFields.push(fieldInfo);
                    }
                }
            }
        }
        
        result.targetFields.push(fieldInfo);
    });
    
    result.summary.total = target.dataHeaders.filter(h => h).length;
    result.summary.mapped = result.mappedFields.length;
    result.summary.missing = result.missingRequiredFields.length + result.missingOptionalFields.length;
    result.summary.required = result.targetFields.filter(f => f.isRequired).length;
    result.summary.requiredMissing = result.missingRequiredFields.length;
    
    return result;
}

function applyManualMappings(mapping, manualMappings, removedMappings, sourceHeaders, targetHeaders) {
    removedMappings.forEach(removed => {
        mapping.columnMappings = mapping.columnMappings.filter(
            m => m.targetIndex !== removed.targetIndex
        );
    });
    
    manualMappings.forEach(manual => {
        mapping.columnMappings = mapping.columnMappings.filter(
            m => m.targetIndex !== manual.target
        );
        
        const sourceField = sourceHeaders[manual.source];
        const targetField = targetHeaders[manual.target];
        
        mapping.columnMappings.push({
            sourceIndex: manual.source,
            targetIndex: manual.target,
            sourceField: sourceField,
            targetField: targetField,
            score: 100,
            matchType: 'manual'
        });
    });
    
    console.log(`  应用手动映射: ${manualMappings.length} 个`);
    console.log(`  移除映射: ${removedMappings.length} 个`);
}

module.exports = {
    buildFieldMapping,
    previewTransformation,
    applyManualMappings
};
